// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5756.RecinCrew2020.subsystems;

import org.usfirst.frc5756.RecinCrew2020.Robot;
import org.usfirst.frc5756.RecinCrew2020.commands.Drive;

import edu.wpi.first.wpilibj.command.Subsystem;

public class DriveTrain extends Subsystem {

    public DriveTrain() {
      
    }

    @Override
    public void initDefaultCommand() {
        stop();
        setDefaultCommand(new Drive());

    }

    @Override
    public void periodic() {
        

    }

    public void drive(double velocity, double rotation) {
        Robot.robotMap.differentialDrive.arcadeDrive(velocity, rotation);
    }

    public void stop() {
        drive(0, 0);
    }
}

