// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5756.RecinCrew2020.subsystems;


import org.usfirst.frc5756.RecinCrew2020.Robot;

import edu.wpi.first.wpilibj.command.Subsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class PowerCellController extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public PowerCellController() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        //Robot.robotMap.powercellCollector.set(ControlMode.PercentOutput, 0);
        //Robot.robotMap.powercellCollector.set(ControlMode.PercentOutput, 0);
        Robot.robotMap.powercellShooter.set(0);
        Robot.robotMap.powercellShooter2.set(0);
        //Robot.robotMap.powercellFeeder.set(ControlMode.PercentOutput, 0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        //TODO: Write else if for a powercellOuttakeButtonSlow, for feeding into low target
       if (Robot.oi.powerCellWindowWhiperButton.get()) {
            powercellIn(1.0);
            //powerCellFeed(1);
            powercellOut(0);
        } else if (Robot.oi.powercellOuttakeButton.get()) {
            powercellIn(0);
            //powerCellFeed(0);
            powercellOut(0.65);
        
        } else {
            powercellIn(0);
            //powerCellFeed(0);
            powercellOut(0);
        }
    }

    public void powercellIn(double speed) {
        //Robot.robotMap.powercellCollector.set(ControlMode.PercentOutput, -speed);
        
    }

    public void powerCellFeed(double speed) {
        //Robot.robotMap.powercellFeeder.set(ControlMode.PercentOutput, speed);
    }

    public void powercellOut(double speed) {
        Robot.robotMap.powercellShooter.set(-speed);
        Robot.robotMap.powercellShooter2.set(speed);
    }


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

